/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ActionSheet {}
  interface AppHome {}
  interface AppRoot {}
}

declare global {


  interface HTMLActionSheetElement extends Components.ActionSheet, HTMLStencilElement {}
  var HTMLActionSheetElement: {
    prototype: HTMLActionSheetElement;
    new (): HTMLActionSheetElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };
  interface HTMLElementTagNameMap {
    'action-sheet': HTMLActionSheetElement;
    'app-home': HTMLAppHomeElement;
    'app-root': HTMLAppRootElement;
  }
}

declare namespace LocalJSX {
  interface ActionSheet extends JSXBase.HTMLAttributes<HTMLActionSheetElement> {}
  interface AppHome extends JSXBase.HTMLAttributes<HTMLAppHomeElement> {}
  interface AppRoot extends JSXBase.HTMLAttributes<HTMLAppRootElement> {}

  interface IntrinsicElements {
    'action-sheet': ActionSheet;
    'app-home': AppHome;
    'app-root': AppRoot;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


